global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
  static_configs:
    - targets:
        - 127.0.0.1:9090
- job_name: node
  static_configs:
    - targets:
        - node_exporter:9100
- job_name: cadvisor
  static_configs:
    - targets:
        - cadvisor:8080
- job_name: snmp
  metrics_path: /snmp
  params:
    module:
      - mikrotik
    auth:
      - mikrotik_v2
  static_configs:
    - targets:
        - 192.168.1.1
  relabel_configs:
    - source_labels:
        - __address__
    target_label: __param_target
  - source_labels:
      - __param_target
    target_label: instance
  - target_label: __address__
    replacement: snmp_exporter:9116
- job_name: blackbox-http-public
  metrics_path: /probe
  params:
    module:
      - http_2xx
  static_configs:
    - targets:
        - https://grafana.az-lab.dev
  relabel_configs:
    - source_labels:
        - __address__
      target_label: __param_target
  - source_labels:
      - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
- job_name: blackbox-http-internal
  metrics_path: /probe
  params:
    module:
      - http_2xx_insecure
  static_configs:
    - targets:
        - https://crs309.home.arpa
  relabel_configs:
    - source_labels:
        - __address__
      target_label: __param_target
  - source_labels:
      - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
- job_name: blackbox-http-protected
  metrics_path: /probe
  params:
    module:
      - http_2xx_allow_401_403
  static_configs:
    - targets:
        - https://traefik.az-lab.dev/dashboard/#/
  relabel_configs:
    - source_labels:
        - __address__
      target_label: __param_target
  - source_labels:
      - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
